// Auto-generated by svg-to-component.ts
// Do not edit manually

// Pin Icons
export { default as AddPinIcon } from './components/pin/AddPin';
export { default as HomePinIcon } from './components/pin/HomePin';
export { default as MarkPinIcon } from './components/pin/MarkPin';
export { default as NavigationPinIcon } from './components/pin/NavigationPin';
export { default as PinIcon } from './components/pin/Pin';

// Vehicle Icons
export { default as BigTruckIcon } from './components/vehicle/BigTruck';
export { default as MiniTruckIcon } from './components/vehicle/MiniTruck';
export { default as MotobikeIcon } from './components/vehicle/Motorbike';

// Weather Icons
export { default as SunnyIcon } from './components/weather/Sunny';

